apiVersion: v1
data:
  JAVA_OPTS: {{ .Values.appSettings.javaOpts }}
  AWS_REGION: {{ .Values.awsSettings.region }}
  EXAMPLE_SECRET_ID: {{ .Values.appSettings.exampleSecretId }}
  DB_NAME: {{ .Values.appSettings.db.dbname }}
  DB_HOSTNAME: {{ .Values.appSettings.db.hostname }}
  DB_USERNAME: {{ .Values.appSettings.db.username }}
  DB_PASSWORD: {{ .Values.appSettings.db.password }}
{{- if .Values.datadog.enabled }}
  DD_ENV: {{ .Values.cluster.namespace }}
  DD_LOGS_INJECTION: {{ .Values.datadog.logsInjection | quote }}
  DD_HTTP_SERVER_ERROR_STATUSES: {{ .Values.datadog.apmHttpErrorStatuses }}
  DD_SERVICE: zio-http-poc-service
  DD_SERVICE_MAPPING: "postgresql:zio-http-poc-db, java-aws-sdk:zio-http-poc-service"
  DD_TRACE_SAMPLE_RATE: {{ .Values.datadog.traceSampleRate | quote }}
  DD_VERSION: {{ .Chart.Version | quote }}
{{- end }}
kind: ConfigMap
metadata:
{{- if .Values.configMap.preserveOldReleases }}
  annotations:
      "helm.sh/resource-policy": keep
{{- end }}
  name: zio-http-poc-service-env-{{ include "zio-http-poc-chart.cm-suffix" . }}
  namespace: {{ .Values.cluster.namespace }}
