apiVersion: v1
data:
  nginx.conf: |-
    server {
      listen {{ .Values.nginxSettings.port }} default_server;
      listen [::]:{{ .Values.nginxSettings.port }} default_server;

      server_name {{ .Values.cluster.namespace}}-zio-http-poc.burnerapp.com;
      access_log  off;
      server_tokens off;
      keepalive_requests 100;
      keepalive_time 20s;

      location / {
          proxy_pass http://localhost:{{ .Values.appSettings.port }}/;
      }
    }
kind: ConfigMap
metadata:
  name: nginx-zio-http-poc-service
  namespace: {{ .Values.cluster.namespace }}
