apiVersion: v1
kind: ServiceAccount
metadata:
  name: zio-http-poc-service
  namespace: {{ .Values.cluster.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.awsSettings.iamRoleArnBase }}/{{ .Values.awsSettings.iamRole }}
